name: Build and Push Docker Image

on:
  push:
    branches:
      - main
  workflow_dispatch:

permissions:
  contents: read
  packages: write

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Debug repository files
        run: |
          echo "PWD:"
          pwd
          echo "FILES:"
          ls -la
          echo "DOCKERFILE CONTENT:"
          cat Dockerfile

      - name: Login to GHCR
        run: |
          echo "${{ secrets.GITHUB_TOKEN }}" | docker login ghcr.io -u "${{ github.actor }}" --password-stdin

      - name: Build Docker image
        run: |
          docker build -t ghcr.io/kobyla1993-beep/wan-runpod-worker:latest -f Dockerfile .

      - name: Push Docker image
        run: |
          docker push ghcr.io/kobyla1993-beep/wan-runpod-worker:latest